# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3373719da4b0103490e9ac52eb542807404eca2a02cd1c2e65c8692339f58e5370ad55a551e0f007436b331665ad2d48349ad715994d2dfdfa6799b08ae09060

test:
  secret_key_base: 078c41f9c5e15458b340eec996b94b6e9ac8f2f04f96b1cda3ef22acb8b9756092e4d3581c500356f9302526cf174eea63e210876cf80ecb82479221a710c671

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
